"use client";
import { useEffect, useState, type FormEvent } from "react";
import type { AccountUser } from "@/lib/account-types";
import { sessionInputSchema } from "@/lib/validation";
import { downloadJson, api } from "@/lib/client-api";
function clearAccountCache(id: string) {
  for (let i = localStorage.length - 1; i >= 0; i--) { const key = localStorage.key(i); if (key?.endsWith(":" + id)) localStorage.removeItem(key); }
}
export default function AccountPanel({ account }: { account: AccountUser | null }) {
  const [mode, setMode] = useState<"login" | "register" | "recover">("login");
  const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [recoveryCode, setRecoveryCode] = useState(""); const [acknowledged, setAcknowledged] = useState(false);
  const [backups, setBackups] = useState<{ id: string; date: string }[]>([]);
  const [selectedBackup, setSelectedBackup] = useState("");
  const [integrationTokens, setIntegrationTokens] = useState<{ id: string; name: string; scopes: ("read" | "write")[]; createdAt: string; revoked: boolean }[]>([]);
  const [integrationName, setIntegrationName] = useState("");
  const [integrationScopes, setIntegrationScopes] = useState<("read" | "write")[]>(["read", "write"]);
  const [newIntegrationToken, setNewIntegrationToken] = useState("");
  const [profile, setProfile] = useState({ role: account?.role ?? "athlete", bodyweightKg: account?.bodyweightKg ?? null, name: account?.name ?? "", sport: account?.sport ?? "Field & court athlete", timezone: account?.timezone ?? Intl.DateTimeFormat().resolvedOptions().timeZone, weightUnit: account?.weightUnit ?? "kg", heightUnit: account?.heightUnit ?? "in" });
  async function action(work: () => Promise<void>) { setBusy(true); setError(""); setMessage(""); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : "Request failed."); } finally { setBusy(false); } }
  useEffect(() => {
    if (!account) return;
    let stopped = false;
    void api<{ tokens: typeof integrationTokens }>("/api/account/integrations").then(result => { if (!stopped) setIntegrationTokens(result.tokens); }).catch(e => { if (!stopped) setError(e instanceof Error ? e.message : "Integration tokens could not be loaded."); });
    return () => { stopped = true; };
  }, [account]);
  function authenticate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const fields = new FormData(event.currentTarget);
    void action(async () => {
      const result = await api<{ recoveryCode?: string }>("/api/auth/" + mode, "POST", { ...profile, email: fields.get("email"), password: fields.get("password"), recoveryCode: fields.get("recoveryCode") });
      if (result.recoveryCode) setRecoveryCode(result.recoveryCode); else window.location.reload();
    });
  }
  async function importBrowser() {
    const raw = localStorage.getItem("loadfactor-workspace-v2");
    const source = raw ? JSON.parse(raw).records : JSON.parse(localStorage.getItem("loadfactor-sessions-v1") ?? "[]");
    if (!Array.isArray(source)) throw new Error("Browser session data is unreadable.");
    const records = source.map(entry => { const input = sessionInputSchema.safeParse(entry?.session); if (!input.success || typeof entry?.session?.id !== "string") throw new Error("One or more browser sessions are invalid. Export your local data before repairing it."); return { migrationId: entry.session.id, input: input.data }; });
    let imported = 0;
    for (let index = 0; index < records.length; index += 50) imported += (await api<{ imported: number }>("/api/account/import", "POST", { records: records.slice(index, index + 50) })).imported;
    setMessage(imported + " sessions imported. Previously imported sessions were skipped."); window.dispatchEvent(new Event("loadfactor-sync"));
  }
  return <section id="account" className="panel account-panel">
    <div className="section-title"><div><span className="eyebrow">Account</span><h2>{account ? "Account & data" : "Save your progress across devices"}</h2></div>{account && <button disabled={busy} className="secondary-button" onClick={() => void action(async () => { await api("/api/auth/logout", "POST"); window.location.reload(); })}>Sign out</button>}</div>
    {!account ? <>
      <p className="account-description">Create an account to save workouts on the server and access them from another device. Your browser demo remains available.</p>
      <div className="phase-controls" role="group" aria-label="Account access">{(["login", "register", "recover"] as const).map(value => <button type="button" disabled={busy} className="secondary-button" aria-pressed={mode === value} key={value} onClick={() => { setMode(value); setError(""); }}>{value === "login" ? "Sign in" : value === "register" ? "Create account" : "Recover password"}</button>)}</div>
      <form onSubmit={authenticate}><fieldset disabled={busy}><div className="account-grid">
        <label className="field-label">Email<input name="email" type="email" autoComplete="email" maxLength={254} required/></label>
        <label className="field-label">{mode === "recover" ? "New password" : "Password"}<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={mode === "login" ? 1 : 12} maxLength={128} required/></label>
        {mode === "recover" && <label className="field-label">Private recovery code<input name="recoveryCode" autoComplete="off" required maxLength={100}/></label>}
        {mode === "register" && <><label className="field-label">Account type<select value={profile.role} onChange={e => setProfile({ ...profile, role: e.target.value as "athlete" | "coach" })}><option value="athlete">Athlete</option><option value="coach">Coach</option></select></label><label className="field-label">Athlete name<input required maxLength={80} value={profile.name} onChange={e => setProfile({ ...profile, name: e.target.value })}/></label><label className="field-label">Sport<input required maxLength={80} value={profile.sport} onChange={e => setProfile({ ...profile, sport: e.target.value })}/></label><label className="field-label">Timezone<input required maxLength={100} value={profile.timezone} onChange={e => setProfile({ ...profile, timezone: e.target.value })} placeholder="Africa/Tripoli"/></label></>}
      </div><p className="account-description">{mode === "recover" ? "Enter the private code saved when you created your account. Recovery resets your password, signs out existing devices, and issues a new code." : mode === "register" ? "Use at least 12 password characters. You will receive a private recovery code to save." : "Sign in to the same account on each device to sync your workouts."}</p><button className="primary-button" type="submit">{busy ? "Working..." : mode === "login" ? "Sign in" : mode === "register" ? "Create account" : "Reset password"}</button></fieldset></form>
    </> : <>
      <p className="account-description">Signed in as {account.email}. Workouts sync automatically every 15 seconds and when you return to this window.</p>
      <form onSubmit={e => { e.preventDefault(); void action(async () => { await api("/api/account", "PATCH", profile); window.location.reload(); }); }}><fieldset disabled={busy}><div className="account-grid">
        <label className="field-label">Account type<select value={profile.role} onChange={e => setProfile({ ...profile, role: e.target.value as "athlete" | "coach" })}><option value="athlete">Athlete</option><option value="coach">Coach</option></select></label><label className="field-label">Name<input value={profile.name} required maxLength={80} onChange={e => setProfile({ ...profile, name: e.target.value })}/></label><label className="field-label">Sport<input value={profile.sport} required maxLength={80} onChange={e => setProfile({ ...profile, sport: e.target.value })}/></label><label className="field-label">Timezone<input value={profile.timezone} required maxLength={100} onChange={e => setProfile({ ...profile, timezone: e.target.value })}/></label>
        <label className="field-label">Default bodyweight (kg)<input type="number" min="1" max="500" step="any" value={profile.bodyweightKg ?? ""} onChange={e => setProfile({ ...profile, bodyweightKg: e.target.value ? Number(e.target.value) : null })}/></label><label className="field-label">Weight unit<select value={profile.weightUnit} onChange={e => setProfile({ ...profile, weightUnit: e.target.value as "kg" | "lbs" })}><option value="kg">kg</option><option value="lbs">lbs</option></select></label><label className="field-label">Jump unit<select value={profile.heightUnit} onChange={e => setProfile({ ...profile, heightUnit: e.target.value as "cm" | "in" })}><option value="cm">cm</option><option value="in">in</option></select></label>
      </div><button className="secondary-button" type="submit">Save profile & preferences</button></fieldset></form>
      <div className="phase-controls"><button disabled={busy} className="secondary-button" onClick={() => void action(importBrowser)}>Import saved browser sessions</button><button disabled={busy} className="secondary-button" onClick={() => void action(async () => downloadJson("loadfactor-account.json", await api("/api/account/export")))}>Download account data</button></div>
      <details><summary>Authorized integrations & API tokens</summary><p className="account-description">Tokens grant only the scopes selected below. They are shown once, stored on the server as hashes, and can be revoked here. Treat them like passwords and never put them in browser code or source control. API reference: <a href="/api/openapi" target="_blank" rel="noreferrer">OpenAPI JSON</a>.</p><form onSubmit={event => { event.preventDefault(); void action(async () => { const token = await api<{ id: string; token: string }>("/api/account/integrations", "POST", { name: integrationName, scopes: integrationScopes }); setNewIntegrationToken(token.token); setIntegrationName(""); setIntegrationTokens((await api<{ tokens: typeof integrationTokens }>("/api/account/integrations")).tokens); }); }}><label className="field-label">Integration name<input required maxLength={80} value={integrationName} onChange={event => setIntegrationName(event.target.value)}/></label><div className="phase-controls">{(["read", "write"] as const).map(scope => <label key={scope}><input type="checkbox" checked={integrationScopes.includes(scope)} onChange={event => setIntegrationScopes(current => event.target.checked ? [...current, scope] : current.filter(value => value !== scope))}/> {scope === "read" ? "Read sessions" : "Write sessions"}</label>)}</div><button className="secondary-button" disabled={busy || integrationScopes.length === 0}>Create API token</button></form>{newIntegrationToken && <label className="field-label">Copy this token now; it will not be shown again<input readOnly value={newIntegrationToken}/></label>}{integrationTokens.map(token => <div className="template-item" key={token.id}><span>{token.name} / {token.scopes.join(", ")} / {token.revoked ? "Revoked" : "Active"}</span>{!token.revoked && <button type="button" className="text-button" disabled={busy} onClick={() => void action(async () => { await api("/api/account/integrations", "DELETE", { id: token.id }); setIntegrationTokens((await api<{ tokens: typeof integrationTokens }>("/api/account/integrations")).tokens); if (newIntegrationToken) setNewIntegrationToken(""); })}>Revoke</button>}</div>)}</details>
      <p className="account-description">Import copies your saved demo sessions into this account without changing the local originals. Repeated imports skip records already migrated.</p>
      <details><summary>Backups & recovery</summary><p className="account-description">An automatic snapshot is saved on your first visit or change each UTC day. The latest 14 snapshots are kept. Create a snapshot before making larger changes.</p><div className="phase-controls"><button disabled={busy} className="secondary-button" onClick={() => void action(async () => { const data = await api<{ backups: typeof backups }>("/api/account/backups"); setBackups(data.backups); })}>Load backups</button><button disabled={busy} className="secondary-button" onClick={() => void action(async () => { const data = await api<{ backups: typeof backups }>("/api/account/backups", "POST"); setBackups(data.backups); setMessage("Backup created."); })}>Create backup now</button><label className="field-label">Snapshot<select value={selectedBackup} onChange={e => setSelectedBackup(e.target.value)}><option value="">Choose a snapshot</option>{backups.map(b => <option key={b.id} value={b.id}>{b.date} - {b.id.split("-").slice(3, 4).join("")}</option>)}</select></label><button disabled={busy || !selectedBackup} className="secondary-button" onClick={() => { if (window.confirm("Restore this snapshot? It will replace your account's sessions, templates, and custom exercises. Your current data will be backed up first.")) void action(async () => { await api("/api/account/restore", "POST", { backupId: selectedBackup, confirmation: "RESTORE" }); window.location.reload(); }); }}>Restore selected snapshot</button></div></details>
      <details><summary>Delete account</summary><p className="account-description">Permanently remove this account, workouts, sign-ins, templates, custom exercises, and server backups. Download your account data first if you want a copy.</p><form onSubmit={e => { e.preventDefault(); const fields = new FormData(e.currentTarget); void action(async () => { await api("/api/account", "DELETE", { password: fields.get("password"), confirmation: fields.get("confirmation") }); try { clearAccountCache(account.id); } catch { /* Server deletion has completed. */ } window.location.reload(); }); }}><fieldset disabled={busy}><div className="account-grid"><label className="field-label">Current password<input name="password" type="password" autoComplete="current-password" required maxLength={128}/></label><label className="field-label">Type DELETE to confirm<input name="confirmation" required pattern="DELETE"/></label></div><button type="submit" className="secondary-button">Permanently delete account</button></fieldset></form></details>
    </>}
    {error && <p className="error-message" role="alert">{error}</p>}{message && <p className="success-message" role="status">{message}</p>}
    {recoveryCode && <div className="recovery-overlay"><div className="panel recovery-dialog" role="dialog" aria-modal="true" aria-label="Save your recovery code"><h2>Save your private recovery code</h2><p>Keep this code somewhere safe. It lets you reset your password and is shown only now. Each recovery replaces the old code.</p><code>{recoveryCode}</code><button className="secondary-button" onClick={() => downloadJson("loadfactor-recovery-code.json", { recoveryCode })}>Download recovery code</button><label className="recovery-ack"><input type="checkbox" checked={acknowledged} onChange={e => setAcknowledged(e.target.checked)}/>I saved my recovery code.</label><button className="primary-button" disabled={!acknowledged} onClick={() => window.location.reload()}>Continue to my account</button></div></div>}
  </section>;
}
