"use client";

import type { ReactNode } from "react";
import Link from "next/link";
import { ArrowRight, BarChart3, CalendarDays, Check, CheckCircle2, Dumbbell, FileText, HeartPulse, Timer } from "lucide-react";
import BrandMark from "./brand-mark";

export default function ProductIntroduction({ children, onSignIn, onCreateAccount }: { children: ReactNode; onSignIn: () => void; onCreateAccount: () => void }) {
  return <div className="product-site">
    <a className="product-skip" href="#product-content">Skip to content</a>
    <header className="product-header"><Link className="landing-brand" href="/" aria-label="LoadFactor home"><BrandMark/>loadfactor<span className="brand-period">.</span></Link><nav aria-label="Website navigation"><a href="#features">Features</a><a href="#how-it-works">How it works</a></nav><div className="product-header-actions"><button type="button" className="text-button" onClick={onSignIn}>Log in</button><button type="button" className="primary-button" onClick={onCreateAccount}>Get started<ArrowRight size={16}/></button></div></header>
    <main id="product-content" className="product-main">
      <section className="product-hero"><div className="product-hero-copy"><span className="product-kicker"><Dumbbell size={16}/>Your workout notebook, with charts.</span><h1>A plan for today.<br/>A record of <span>your progress.</span></h1><p>Build your workout, record each set, and see your results. Keep strength, jumps, sprints, and recovery in one training log.</p><div className="product-hero-actions"><button type="button" className="primary-button" onClick={onCreateAccount}>Create your account<ArrowRight size={18}/></button><a className="secondary-button" href="#features">Take a look inside</a></div><p className="product-device-note">Use it in your browser on your phone or computer.</p></div><div className="product-hero-visual"><DashboardPreview/><div className="product-floating-note"><CheckCircle2 size={20}/><div><strong>Finish a workout. See your results.</strong><span>Sets, effort, volume, and measured attempts.</span></div></div></div></section>
      <div className="product-capabilities" aria-label="Training tools"><span><FileText size={18}/>Workout plans</span><span><Dumbbell size={18}/>Set-by-set logging</span><span><BarChart3 size={18}/>Session charts</span><span><CalendarDays size={18}/>Weekly schedule</span><span><HeartPulse size={18}/>Daily check-ins</span></div>
      <section id="features" className="product-features" aria-labelledby="features-heading"><div className="product-section-heading"><span className="product-kicker">Inside LoadFactor</span><h2 id="features-heading">From your first set to your weekly review.</h2><p>Simple tools for planning what you’ll do and keeping track of what you actually did.</p></div>
        <FeatureRow visual={<WorkoutPhone/>} label="During training" title="Log your workout as you go." description="Record the weight, reps, and effort for each set. For jump and sprint sessions, enter the measurements you took." items={["Strength, jump, and sprint exercises", "Warm-up sets, drop sets, and exercise notes", "Rest timer and reusable workout templates"]}/>
        <FeatureRow reverse visual={<ProgressPreview/>} label="After your workout" title="See the results of the session you just saved." description="Your saved workout becomes a summary with charts. Review each set or attempt, then follow your training over time." items={["Weight and reps for each strength set", "Jump measurements and sprint times", "Weekly volume and performance history"]}/>
        <FeatureRow visual={<DocumentPreview/>} label="Before training" title="Write tomorrow’s workout like a document." description="Start with your objective and warm-up. Arrange the exercises, add sets and rest periods, and save the plan to your schedule." items={["Exercise order, sets, reps, and instructions", "Warm-up, cool-down, and session notes", "Print your plan or save it as a PDF"]}/>
      </section>
      <section id="how-it-works" className="product-steps" aria-labelledby="steps-heading"><div className="product-section-heading"><span className="product-kicker">Getting started</span><h2 id="steps-heading">Plan. Train. Review.</h2></div><div className="product-step-grid">{[{ title: "Write your plan", text: "Choose a date and write the exercises you want to do.", icon: FileText }, { title: "Record your session", text: "Log your actual sets, effort, and measured results.", icon: Dumbbell }, { title: "Review your results", text: "See the workout summary and compare your training over time.", icon: BarChart3 }].map((step, index) => <article key={step.title}><div><span>0{index + 1}</span><step.icon size={22}/></div><h3>{step.title}</h3><p>{step.text}</p></article>)}</div></section>
      <section id="get-started" className="product-account" aria-label="Sign in or create an account"><div><span className="product-kicker">Your training starts here</span><h2>Keep a useful record<br/>of every workout.</h2><p>Create an account or sign in to open your training workspace.</p><div className="product-storage-note"><FileText size={20}/><p>Workouts are currently saved in the browser you use. Cloud workout sync is not connected to Firebase sign-in yet.</p></div></div>{children}</section>
    </main>
    <footer className="product-footer"><Link className="landing-brand" href="/">loadfactor<span className="brand-period">.</span></Link><span>Workout plans and results.</span><a href="#product-content">Back to top ↑</a></footer>
  </div>;
}

function PreviewLabel() { return <span className="product-preview-label">Illustrative app preview · sample values</span>; }

function FeatureRow({ visual, label, title, description, items, reverse = false }: { visual: ReactNode; label: string; title: string; description: string; items: string[]; reverse?: boolean }) {
  return <article className={"product-feature-row" + (reverse ? " product-feature-reverse" : "")}><div className="product-feature-visual">{visual}</div><div className="product-feature-copy"><span className="product-kicker">{label}</span><h3>{title}</h3><p>{description}</p><ul>{items.map(item => <li key={item}><CheckCircle2 size={19}/>{item}</li>)}</ul></div></article>;
}

function DashboardPreview() {
  return <figure className="product-dashboard"><figcaption><span><span className="preview-dot"/>loadfactor.</span><PreviewLabel/></figcaption><div className="preview-dashboard-body"><div className="preview-sidebar" aria-hidden="true"><span className="preview-nav-active"><BarChart3 size={14}/>Overview</span><span><Dumbbell size={14}/>Log workout</span><span><FileText size={14}/>Daily workout</span><span><CalendarDays size={14}/>Schedule</span></div><div className="preview-dashboard-content"><div className="preview-heading"><div><small>Training overview</small><strong>Your week in training</strong></div><span className="preview-pill">Weekly view</span></div><div className="preview-stats"><div><span>Workouts</span><strong>3</strong></div><div><span>Sets</span><strong>24</strong></div><div><span>Average effort</span><strong>7.2<small> / 10</small></strong></div></div><div className="preview-chart-panel"><div><strong>Training volume</strong><span>Sample weekly values · kg</span></div><PreviewChart variant="bars"/></div><div className="preview-workout-row"><span className="preview-workout-icon"><Dumbbell size={18}/></span><div><strong>Lower body strength</strong><span>6 exercises · 18 sets</span></div><CheckCircle2 size={18}/></div></div></div></figure>;
}

function WorkoutPhone() {
  return <figure className="product-phone-stage"><div className="product-phone"><div className="phone-speaker" aria-hidden="true"/><div className="phone-topline"><span>9:41</span><span>LoadFactor</span></div><div className="phone-title"><h4>Log workout</h4><span>Lower body</span></div><div className="phone-session-stats"><div><span>Sets</span><strong>3</strong></div><div><span>Volume</span><strong>960 kg</strong></div><div><span>Effort</span><strong>7/10</strong></div></div><div className="phone-exercise-heading"><Dumbbell size={18}/><strong>Back Squat</strong></div><div className="phone-set-table"><div><span>Set</span><span>kg</span><span>Reps</span><span>Done</span></div>{[1, 2, 3].map(set => <div key={set}><span>{set}</span><strong>40</strong><strong>8</strong><Check size={16}/></div>)}</div><div className="phone-rest"><Timer size={16}/><span>Rest timer</span><strong>1:30</strong></div><div className="phone-save" aria-hidden="true">Save session<ArrowRight size={16}/></div><PreviewLabel/></div><figcaption className="phone-side-note"><CheckCircle2 size={20}/><strong>One row per set.</strong><span>Record what you actually did.</span></figcaption></figure>;
}

function ProgressPreview() {
  return <figure className="product-progress-preview"><div className="preview-heading"><div><small>Workout results</small><strong>Sprint training</strong></div><span className="preview-pill">Saved</span></div><PreviewLabel/><div className="preview-result-stats"><div><span>Best time</span><strong>3.12 <small>sec</small></strong></div><div><span>Attempts</span><strong>4</strong></div><div><span>Distance</span><strong>20 <small>m</small></strong></div></div><div className="preview-chart-panel"><div><strong>Time per attempt</strong><span>Lower time is faster</span></div><PreviewChart variant="line"/></div><p className="preview-chart-note">Charts use the measurements recorded in your session.</p></figure>;
}

function DocumentPreview() {
  return <figure className="product-document-preview"><div className="preview-document-toolbar"><FileText size={16}/><span>Daily workout</span><span>Scheduled</span></div><div className="preview-paper"><small>LoadFactor / Workout plan</small><h4>Lower body strength</h4><p>Session objective: practice controlled, consistent reps.</p><div className="preview-paper-section"><strong>Warm-up</strong><p>5 minutes easy movement, then dynamic mobility.</p></div><div className="preview-paper-section"><strong>Main workout</strong><div><span>01</span><strong>Back Squat</strong><p>3 sets × 8 reps · 90 seconds rest</p></div><div><span>02</span><strong>Romanian Deadlift</strong><p>3 sets × 8 reps · 90 seconds rest</p></div></div><div className="preview-paper-section"><strong>Cool-down</strong><p>Easy walk and mobility.</p></div><PreviewLabel/></div></figure>;
}

function PreviewChart({ variant }: { variant: "bars" | "line" }) {
  return <svg className="product-preview-chart" viewBox="0 0 400 190" role="img" aria-label={variant === "bars" ? "Illustrative weekly volume chart using sample values" : "Illustrative sprint chart: sample times of 3.42, 3.28, 3.35, and 3.12 seconds"}><g stroke="#e9e7dd" strokeDasharray="3 5">{[30, 70, 110, 150].map(y => <line key={y} x1="35" x2="385" y1={y} y2={y}/>)}</g>{variant === "bars" ? <><g fill="#e7ba22">{[80, 115, 97, 140].map((height, index) => <rect key={index} x={65 + index * 82} y={150 - height} width="38" height={height} rx="5"/>)}</g><g fill="#697079" fontSize="11" textAnchor="middle">{["Week 1", "Week 2", "Week 3", "Week 4"].map((text, index) => <text key={text} x={84 + index * 82} y="178">{text}</text>)}</g></> : <><path d="M55 35 L155 92 L255 64 L355 150 L355 155 L55 155 Z" fill="#f5cc3522"/><path d="M55 35 L155 92 L255 64 L355 150" fill="none" stroke="#a67c00" strokeWidth="3" strokeLinejoin="round"/>{[[55,35,"3.42"],[155,92,"3.28"],[255,64,"3.35"],[355,150,"3.12"]].map(([x,y,value], index) => <g key={index}><circle cx={Number(x)} cy={Number(y)} r="5" fill="#a67c00" stroke="#fff" strokeWidth="2"/><text x={Number(x)} y={Number(y) - 12} textAnchor="middle" fontSize="12" fill="#454b55">{value}</text><text x={Number(x)} y="180" textAnchor="middle" fontSize="11" fill="#697079">Attempt {index + 1}</text></g>)}</>}</svg>;
}
