"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api } from "@/lib/client-api";
import { emptyStrengthSettings, repetitionRecords, strengthCatalog, strengthSeries, weeklyMuscleSets } from "@/lib/strength";
import { strengthSettingsSchema, type StrengthSettings } from "@/lib/validation";
import { muscleGroups, type Exercise, type WeightUnit, type WorkoutSession } from "@/lib/types";
import { weekStart, weightFromKg } from "@/lib/analytics";
const tooltipStyle = { background: "#ffffff", border: "1px solid #deded5", borderRadius: 10, color: "#252a32", fontSize: 12 };
type Props = { sessions: WorkoutSession[]; custom: Exercise[]; today: string; weightUnit: WeightUnit; accountId?: string; settings: StrengthSettings; onSettings: (settings: StrengthSettings) => void };
export default function StrengthDashboard({ sessions, custom, today, weightUnit, accountId, settings, onSettings }: Props) {
  const catalog = strengthCatalog(sessions, custom);
  const [selected, setSelected] = useState("trap-bar-deadlift"), [range, setRange] = useState(90), [week, setWeek] = useState(today);
  const [draft, setDraft] = useState(settings), [alternative, setAlternative] = useState(""), [busy, setBusy] = useState(false), [ready, setReady] = useState(!!accountId), [notice, setNotice] = useState("");
  const exerciseId = catalog.some(e => e.id === selected) ? selected : catalog[0]?.id ?? "", exercise = catalog.find(e => e.id === exerciseId);
  useEffect(() => {
    if (accountId) return;
    const frame = requestAnimationFrame(() => {
      try { const raw = localStorage.getItem("loadfactor-strength-settings-v1"); const value = raw ? strengthSettingsSchema.parse(JSON.parse(raw)) : emptyStrengthSettings; setDraft(value); onSettings(value); }
      catch { setNotice("Strength settings could not be loaded from this browser."); }
      setReady(true);
    });
    return () => cancelAnimationFrame(frame);
  }, [accountId, onSettings]);
  async function saveSettings() {
    setBusy(true); setNotice("");
    try {
      const next = strengthSettingsSchema.parse(draft);
      if (accountId) await api("/api/account/strength", "PUT", next); else localStorage.setItem("loadfactor-strength-settings-v1", JSON.stringify(next));
      onSettings(next); setNotice("Muscle assignments and exercise alternatives saved.");
    } catch (error) { setNotice(error instanceof Error ? error.message : "Could not save strength settings."); }
    finally { setBusy(false); }
  }
  const points = strengthSeries(sessions, exerciseId, today, range), records = repetitionRecords(sessions, exerciseId);
  const estimates = points.flatMap(p => p.estimateKg === null ? [] : [p.estimateKg]), ratios = points.flatMap(p => p.ratio === null ? [] : [p.ratio]);
  const data = points.map(p => ({ ...p, estimate: p.estimateKg === null ? null : Number(weightFromKg(p.estimateKg, weightUnit).toFixed(1)), workingVolume: Number(weightFromKg(p.workingVolumeKg, weightUnit).toFixed(1)), warmupVolume: Number(weightFromKg(p.warmupVolumeKg, weightUnit).toFixed(1)) }));
  const validWeek = /^\d{4}-\d{2}-\d{2}$/.test(week) && !Number.isNaN(new Date(week + "T12:00:00").getTime()), muscleSets = weeklyMuscleSets(sessions, validWeek ? week : today, settings);
  const assigned = draft.muscles[exerciseId] ?? exercise?.muscleGroups ?? [], alternatives = draft.alternatives[exerciseId] ?? [];
  return <section id="strength" className="panel account-panel scroll-mt-6">
    <div className="section-title"><div><span className="eyebrow">STRENGTH TRACKING</span><h2>Build your strength baseline</h2></div></div>
    <div className="phase-controls"><label className="field-label">Strength exercise<select value={exerciseId} onChange={e => { setSelected(e.target.value); setAlternative(""); }}>{catalog.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label className="field-label">Trend window<select value={range} onChange={e => setRange(Number(e.target.value))}>{[30, 90, 180, 365].map(days => <option value={days} key={days}>{days} days</option>)}</select></label></div>
    <dl className="history-stats"><div><dt>Best estimated 1RM ({weightUnit})</dt><dd>{estimates.length ? weightFromKg(Math.max(...estimates), weightUnit).toFixed(1) : "-"}</dd></div><div><dt>Best estimate / session bodyweight</dt><dd>{ratios.length ? Math.max(...ratios).toFixed(2) + "x" : "-"}</dd></div><div><dt>Exercise volume in window ({weightUnit})</dt><dd>{weightFromKg(points.reduce((n, p) => n + p.workingVolumeKg + p.warmupVolumeKg, 0), weightUnit).toLocaleString(undefined, { maximumFractionDigits: 0 })}</dd></div></dl>
    <p className="account-description">Estimates use working strength sets with 1-10 reps and positive external load. Warm-ups and drop stages are excluded. Epley-style calculation: load x (1 + reps / 30); singles use the logged load. These are estimates from completed reps, not tested maximums. <a href="https://mladenjovanovic.github.io/STMr/reference/max_perc_1RM.html" target="_blank" rel="noreferrer">Formula reference</a></p>
    <div className="strength-charts"><div className="chart-panel"><h3>Estimated 1RM trend ({weightUnit})</h3><div className="chart" role="img" aria-label="Estimated one rep maximum for each training session">{estimates.length ? <ResponsiveContainer width="100%" height="100%" minWidth={0}><LineChart data={data}><CartesianGrid stroke="#e6e5dc" strokeDasharray="3 5"/><XAxis dataKey="date" tick={{ fill: "#606875", fontSize: 10 }} minTickGap={40}/><YAxis tick={{ fill: "#606875", fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={value => [String(value) + " " + weightUnit, "Estimated 1RM"]}/><Line dataKey="estimate" stroke="#c99b0b" strokeWidth={2} dot={{ r: 3 }} connectNulls={false}/></LineChart></ResponsiveContainer> : <p className="empty">Log a loaded working set of 1-10 reps for this exercise.</p>}</div></div><div className="chart-panel"><h3>Exercise volume by session ({weightUnit})</h3><div className="chart" role="img" aria-label="Working and warm-up volume by session">{points.length ? <ResponsiveContainer width="100%" height="100%" minWidth={0}><BarChart data={data}><CartesianGrid stroke="#e6e5dc" strokeDasharray="3 5"/><XAxis dataKey="date" tick={{ fill: "#606875", fontSize: 10 }} minTickGap={40}/><YAxis tick={{ fill: "#606875", fontSize: 10 }}/><Tooltip contentStyle={tooltipStyle} formatter={(value, name) => [String(value) + " " + weightUnit, name === "warmupVolume" ? "Warm-up volume" : "Working + drop volume"]}/><Bar dataKey="workingVolume" stackId="volume" fill="#6c7280"/><Bar dataKey="warmupVolume" stackId="volume" fill="#f5cc35"/></BarChart></ResponsiveContainer> : <p className="empty">No sessions for this exercise in the selected window.</p>}</div></div></div>
    <p className="account-description">Blue volume includes working sets and each drop stage; purple includes warm-ups. Bodyweight ratios use the bodyweight recorded with that session and external load only. Add session bodyweight in the logger to track ratios.</p>
    <details><summary>View trend values and bodyweight ratios</summary><div className="table-scroll"><table><thead><tr><th>Session</th><th>Date</th><th>Estimated 1RM ({weightUnit})</th><th>Bodyweight ({weightUnit})</th><th>Ratio</th></tr></thead><tbody>{points.map(p => <tr key={p.id}><td><Link className="text-button" href={"/sessions/" + p.id}>{p.title}</Link></td><td>{p.date}</td><td>{p.estimateKg === null ? "-" : weightFromKg(p.estimateKg, weightUnit).toFixed(1)}</td><td>{p.bodyweightKg === null ? "-" : weightFromKg(p.bodyweightKg, weightUnit).toFixed(1)}</td><td>{p.ratio?.toFixed(2) ?? "-"}</td></tr>)}{!points.length && <tr><td colSpan={5}>No strength sessions in this window.</td></tr>}</tbody></table></div></details>
    <h3>All-time records by rep count</h3><p className="account-description">Highest external load at each exact logged rep count; working sets only.</p><div className="table-scroll"><table><thead><tr><th>Reps</th><th>Best load ({weightUnit})</th><th>Date</th><th>Session</th></tr></thead><tbody>{records.map(record => <tr key={record.reps}><td>{record.reps}</td><td>{weightFromKg(record.weightKg, weightUnit).toFixed(1)}</td><td>{record.date}</td><td><Link className="text-button" href={"/sessions/" + record.sessionId}>View session</Link></td></tr>)}{!records.length && <tr><td colSpan={4}>No loaded working-set records yet.</td></tr>}</tbody></table></div>
    <div className="phase-controls"><h3>Weekly sets by muscle group</h3><label className="field-label">Choose a date in the training week<input type="date" value={week} onChange={e => setWeek(e.target.value)}/></label></div><p className="account-description">Week of {weekStart(validWeek ? week : today)}. Warm-ups are excluded. Each working set and drop stage counts once for every assigned muscle group, so muscle totals can overlap. Unassigned exercises appear separately. Current assignments apply to historical weeks.</p><div className="muscle-counts">{muscleSets.map(group => <div key={group.group}><span>{group.group}</span><strong>{group.total}</strong><small>{group.working} working + {group.drop} drop stages</small></div>)}</div>
    <details><summary>Muscle assignments & your exercise alternatives</summary><p className="account-description">Configure {exercise?.name ?? "this exercise"}. Alternatives are your own saved choices; select them from the logger without sharing records across exercises.</p><div className="muscle-options">{muscleGroups.map(group => <label key={group}><input type="checkbox" checked={assigned.includes(group)} disabled={!ready || busy} onChange={e => setDraft(current => ({ ...current, muscles: { ...current.muscles, [exerciseId]: e.target.checked ? [...assigned, group] : assigned.filter(g => g !== group) } }))}/>{group}</label>)}</div><div className="phase-controls"><label className="field-label">Alternative exercise<select disabled={busy || !ready} value={alternative} onChange={e => setAlternative(e.target.value)}><option value="">Choose an alternative</option>{catalog.filter(e => e.id !== exerciseId && !alternatives.includes(e.id)).map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></label><button className="secondary-button" disabled={!alternative || alternatives.length >= 10 || busy || !ready} onClick={() => { setDraft(current => ({ ...current, alternatives: { ...current.alternatives, [exerciseId]: [...alternatives, alternative] } })); setAlternative(""); }}>Add alternative</button></div>{alternatives.map(id => <div className="template-item" key={id}><span>{catalog.find(e => e.id === id)?.name ?? id}</span><button className="text-button" disabled={busy} onClick={() => setDraft(current => ({ ...current, alternatives: { ...current.alternatives, [exerciseId]: alternatives.filter(value => value !== id) } }))}>Remove alternative</button></div>)}<button className="secondary-button" disabled={busy || !ready} onClick={() => void saveSettings()}>{busy ? "Saving..." : "Save strength settings"}</button></details>{notice && <p className="account-description" role="status">{notice}</p>}
  </section>;
}
